import type { CSSProperties } from "react"

export const styles: Record<string, CSSProperties> = {
  overlay: {
    position:       'fixed',
    inset:          0,
    background:     '#0c1117',
    display:        'flex',
    alignItems:     'center',
    justifyContent: 'center',
    fontFamily:     '"SF Mono", "Fira Code", "Cascadia Code", monospace',
  },
  card: {
    display:        'flex',
    flexDirection:  'column',
    alignItems:     'center',
    gap:            '1.4rem',
    padding:        '2.8rem 3.2rem',
    border:         '1px solid #1e2d3d',
    borderRadius:   '12px',
    background:     '#0d141c',
    animation:      'fadeIn 0.4s ease both',
    maxWidth:       '380px',
    width:          '90%',
  },
  logoRow: {
    display: 'flex',
    gap:     '6px',
  },
  dot: {
    display:      'block',
    width:        '8px',
    height:       '8px',
    borderRadius: '50%',
    background:   '#4f9cf9',
    opacity:      0.7,
    boxShadow:    '0 0 8px #4f9cf9',
  },
  title: {
    margin:        0,
    fontSize:      '1.5rem',
    fontWeight:    600,
    color:         '#dde3ea',
    letterSpacing: '0.04em',
  },
  sub: {
    margin:     0,
    fontSize:   '0.78rem',
    color:      '#4a6070',
    textAlign:  'center',
    lineHeight: 1.7,
  },
  kbd: {
    display:      'inline-block',
    padding:      '1px 5px',
    fontSize:     '0.75rem',
    color:        '#8ba0b2',
    background:   '#131e28',
    border:       '1px solid #1e2d3d',
    borderRadius: '4px',
  },
  form: {
    display:        'flex',
    flexDirection:  'column',
    gap:            '0.75rem',
    width:          '100%',
  },
  input: {
    width:        '100%',
    padding:      '0.65rem 0.9rem',
    fontSize:     '0.9rem',
    fontFamily:   'inherit',
    color:        '#dde3ea',
    background:   '#0c1117',
    border:       '1px solid #1e2d3d',
    borderRadius: '6px',
    outline:      'none',
    boxSizing:    'border-box',
    transition:   'border-color 0.2s',
  },
  inputShake: {
    animation:   'shake 0.4s ease',
    borderColor: '#ff6b6b',
  },
  btn: {
    padding:       '0.65rem 1rem',
    fontSize:      '0.85rem',
    fontFamily:    'inherit',
    letterSpacing: '0.06em',
    color:         '#4f9cf9',
    background:    'transparent',
    border:        '1px solid #4f9cf9',
    borderRadius:  '6px',
    cursor:        'pointer',
    transition:    'background 0.2s, color 0.2s',
  },
}